ALTER TABLE categories ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'system', ADD COLUMN updated_by VARCHAR(255), ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE test_series ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'system', ADD COLUMN updated_by VARCHAR(255);
ALTER TABLE mock_tests ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'system', ADD COLUMN updated_by VARCHAR(255);
ALTER TABLE sections ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'system', ADD COLUMN updated_by VARCHAR(255);
ALTER TABLE questions ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'system', ADD COLUMN updated_by VARCHAR(255);
ALTER TABLE question_translations ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'system', ADD COLUMN updated_by VARCHAR(255), ADD COLUMN deleted_at TIMESTAMP;